### ISSUE TITLE
Case sensitive field names cause errors in lots of contexts.

### ISSUE THREAD

**Issue by acrosman** [SFDO-Tooling/Snowfakery#1019]
Currently if you have two fields with the same name, but with different cases, they will be listed in output as different fields.  But most output targets don't accept that as valid output.

Minimal Example:

```yml
- object: Account
  fields:
      Name:  Company One
- object: Account
  fields:
     name: Company two
```

There are places in more complex use cases where this pattern applies and it's an easy mistake to me.
