### ISSUE TITLE
Bug parsing negative numbers and whitespace

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/Snowfakery#112]
```yaml
- object: foo
  fields:
      good:
        random_number:
          min: ${{ 0 }}
          max: ${{ 1 }}
      good2:
        random_number:
          min: ${{0}}
          max: ${{-1}}
      bad:
        random_number:
          min: ${{ 0 }}
          max: ${{ -1 }}
```
