### ISSUE TITLE
Setting locale and passing arguments

### ISSUE THREAD

**Issue by umeditor** [SFDO-Tooling/Snowfakery#176]
Is it possible to set a locale and call a specific function with an argument? Specifically, I want to call the the paragraphs provider with nb=5 using the 'la' local. I can get it to work using either the local or the argument, but not both.

Setting local:

```
- object: Object__c
  fields:
    Description__c:
      i18n_fake:
        locale: la
        fake: paragraph
```

Passing argument:
```
- object: Object__c
  fields:
    Description__c: ${{fake.paragraphs(nb=5)}}
```

I've tried combining the two without any luck.
