### ISSUE TITLE
Using fields from a macro in a formula.

### ISSUE THREAD

**Issue by acrosman** [SFDO-Tooling/Snowfakery#205]
When trying to use fields on an object that come from a macro in a forumla, the formula evaluates as blank instead of with the expected field value.  I'm doing this in a nested macro context so that may be part of the challenge (and makes the example below a hair more complicated)

Example:  
If I have a Macro that create name fields:
```
- macro: sfContact
  fields:
    Salutation:
      fake: prefix
    FirstName:
      fake: first_name
    LastName:
      fake: last_name
...
```

Trigger that within another macro

```
- macro: HedStudent
  include: sfContact
  fields:
    Title: None
    hed__UniversityEmail__c: ${{FirstName}}.${{LastName}}@example.edu
...
```

And finally create my object:  
```
- object: Contact
  include: HedStudent
...
```

I expected `[FirstName].[LastName]@example.edu`
I got `.@example.edu`
