### ISSUE TITLE
Seeding the Fake Name generation 

### ISSUE THREAD

**Issue by srinathSFDC** [SFDO-Tooling/Snowfakery#230]
We have a use case where we want to write tests to search for a specific name with hard-coded parameters..
SnowFakery generates a new set of data every-time we load the data which makes it impossible to search for a specific user name.

We want to have seeding functionality for Fake fields.

```
   LastName:
      fake: last_name
    FirstName:
      fake: first_name
```

**Comment by acrosman** [comment]
You can add to your recipe records with hard coded values so you can create specific testable records within a larger more complex data set. 

```yaml
- Object: Contact
     Fields:
         LastName:  Smith
         FirstName: Jane

- Object: Contact
   Count: 1000
   Fields:
       LastName:
          fake: last_name
        FirstName:
          fake: first_name
```
(not checked for perfect details, but should be conceptually right)
