### ISSUE TITLE
Consistent addresses

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/Snowfakery#233]
Snowfakery should have a built-in mechanism for generating consistent addresses.

For example, one potential syntax could be:

```
- object: BillingAddress
  vars:
    snowfakery_address_country:
        random_choice:
            - United Kingdom
            - United States
            - Canada
  fields:
    BillingStreet:
      fake: street_address
    BillingCity:
      fake: city
    BillingState:
      fake: state
    BillingPostalCode:
      fake: postalcode
    BillingCountry:
      fake: country
```

This would override the behaviour of faker to hard-code country, select state in an "intelligent" way, and set the locale for all of the rest.
