### ISSUE TITLE
Syntax for Person Accounts in Snowfakery

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/Snowfakery#286]
Proposal 1 is to follow the "internal" syntax that CumulusCI uses after fixing some small issues with CumulusCI.

For a Snowfakery user, this syntax would look like:

```yaml
- object: Account
  fields:
    FirstName:
      fake: first_name
    LastName:
      fake: last_name
    PersonContactId:
      - object: Contact
        fields:
          IsPersonAccount: True
          AccountId:
            reference: Account
```

Proposal 2 is to have a plugin which generates most of that code for you.

```yaml
- plugin: snowfakery.standard_plugins.Salesforce
- object: Account
  fields:
    FirstName:
      fake: first_name
    LastName:
      fake: last_name
    PersonContactId:
      Salesforce.SpecialObject: PersonContact
```
