### ISSUE TITLE
Allow a flatter syntax for function calls

### ISSUE THREAD

**Issue by prescod** [SFDO-Tooling/Snowfakery#311]
At the top level of Snowfakery, the conceptual "first key" selects the "type" of the statement

```
- var: Foo
  default: Bar

- object: Foo
   fields:
       xyzzy: blah
```

The "var" and "default" are at the same level even though the "var" defines the "type" of the statement. This works because at the top-level there are a short list of "keys" available (var/default/object/fields in the example above) and therefore one can easily recognize a variable as any dict with the key "var" in it (no matter the key order) and an object is any dict with the key "object".

At the "function" level, things work differently, because Snowfakery could evolve to have hundreds of functions, especially when they are nested. So Snowfakery forces you to nominate which key is the "function name" like this:

```
        - choice:
              when: ${{gender=='Male'}}
              pick:
                  fake: first_name_male

        - choice:
              when: ${{gender=='Female'}}
              pick:
                fake: first_name_female

        - choice:
              pick:
                fake: first_name
```

This was based on the idea that dict keys are unordered, and therefore we need the user to tell us which one is "primary".

But it turns out that the YAML parser seems to return dict keys in order so we can automatically use the "first" as the function.
