### ISSUE TITLE
Cannot find plugin: snowfakery.standard_plugins.Salesforce.SalesforceQuery

### ISSUE THREAD

**Issue by lucam75** [SFDO-Tooling/Snowfakery#435]
Hello! 

I'm getting this error `Cannot find plugin: snowfakery.standard_plugins.Salesforce.SalesforceQuery` when attempting to generate data based on existent records in my org. I have configured correctly CumulusCI and all other data loads are working well when I'm not using the plugins. 

Any clue about how to solve this error? It seems to me the plugins are not installed, but not sure if this is the case.

I'm running this command `cci task run generate_and_load_from_yaml -o generator_yaml ./datasets/Transactions.recipe.yml -o num_records 300 -o num_records_tablename Transaction__c --org dev`

This is my `Transactions.recipe.yml` file:
```
- plugin: snowfakery.standard_plugins.Salesforce
- plugin: snowfakery.standard_plugins.Salesforce.SalesforceQuery

# randomized values
- object: Transaction__c
  fields:
      Amount__c:
          random_number:
              min: 1
              max: 100000
      Date__c:
          date_between:
              start_date: -1y
              end_date: today
      Description__c:
          fake.text:
              max_nb_chars: 40
      Account__c:
          SalesforceQuery.random_record:
              from: Account
```
