### ISSUE TITLE
Add conditional handling after queries of SF Data

### ISSUE THREAD

**Issue by acrosman** [SFDO-Tooling/Snowfakery#439]
It would be helpful to be able to add data conditionally into a recipe depending on the results of the the `SalesforceQuery.find_record` plugin. Basically being able to add the data if the record is missing, while also being able to safely re-run a recipe against an org to expand a test data set after an initial pass.

Building off the example of the existing feature in the new docs. this would be something like:

```
- plugin: snowfakery.standard_plugins.Salesforce.SalesforceQuery
- object: Contact
  fields:
    FirstName: Bobby
    LastName: McFerrin
  friends:
    - object: CampaignMember
      fields:
        ContactId:
          reference: Contact
        CampaignId:
          if:
            - choice: 
                when: SalesforceQuery.find_record:
                    from: Campaign
                    where: name='Happiness Campaign'
                pick: SalesforceQuery.found_record
            - choice:
                pick: 
                - object: Campaign
                    fields:
                        name: Happiness Campaign
```
