### ISSUE TITLE
Fake.PostalCodeInState does not populate based on state in template

### ISSUE THREAD

**Issue by dcinzona** [SFDO-Tooling/Snowfakery#478]
Recipe:
```yaml
- var: snowfakery_locale
  value: en_US
- object: Address__c
  count: 3
  fields:
    __state:
      fake: State
    __stateAbbr:
      fake: StateAbbr
    __zip: 
      fake: PostalcodeInState
    Person_Account1__c:
      reference: Account
    Name: 
      fake: StreetAddress
    City__c: 
      fake: city
    Country__c: US
    State__c: ${{__stateAbbr}}
    Postal_Code__c: '${{__zip}}'
    Zip__c: '${{__zip}}'
    Type__c: Home
```

Relavent output:

```
Country__c=US, 
State__c=UT, 
Postal_Code__c=3155
```

`3155` is not in the range for `UT`
https://github.com/joke2k/faker/blob/a565d46e928dba18938164de2125de1aabc3f825/faker/providers/address/en_US/__init__.py#L281

Looks like it's in the range for `NH`
