### ISSUE TITLE
Faker provider and associated arguments not being captured in snowfakery versions 2.0 and above ( currently explicitly pointing to 1.12 for expected behavior )

### ISSUE THREAD

**Issue by jdschleicher** [SFDO-Tooling/Snowfakery#537]
reproduced in:
 - versions 2.0 and higher
 - operating systems:  windows and ubuntu virtual machine within github actions

Hi! We have been using snowfakery starting with version 1.12.  We have been working on some poc's for the different field types we were looking to mock within our salesforce instances. When snowfakery jumped to version 2.0 and higher it seemed like some of the faker providers and associated functions were no longer taking in the parameters we were providing. We also saw some runtime errors stating the aliases we were trying that work in 1.12 no longer worked in 2.0 and above.  Below are some examples along with our poc yml file.

- alias no longer accepted:  ${{ fake.random_choice }} --> works  ${{ fake.RandomChoice }} --> doesn't work
- Faker functions not taking in arguments:  When using the ${{ fake.random_sample( elements=('alpha','bravo','charlie','delta','echo','foxtrot') }} we were getting values back 'a', 'c', 'b' or some variation of that.  We originally thought the function was only returning the first character of our elements and we introduced different elements such as ('m,'r','z') and we were still seeing 'b', 'a' , 'c' combinations.  In looking at the faker function within the codebase this may be what looks like default args passed in which would be used when no arguments are provided: https://github.com/joke2k/faker/blob/master/faker/providers/__init__.py
![image](https://user-images.githubusercontent.com/3968818/141618586-2c6f7d2e-fa19-4e0a-b991-798fe80700d7.png)

We have been able to explicitly point to version 1.12 and things have been working as expected but we aren't sure if there is some fundamental approach or piece we are missing on our end that prevents versions 2.0 and above to work as expected with some of the faker providers. Any direction is greatly appreciated!

Below is our poc yml.  

```yaml
- object: SeededRecord__c  
  nickname: SeededRecordRoot  
  count: 1000  
  fields:  
    checkbox1__c:  
        random_choice:
          - 'true'
          - 'false'
    currency1__c:
      fake: pyfloat
    date1__c:
      fake: date
    datetime1__c: ${{ fake.date(pattern='%Y-%m-%d') }}T${{ fake.pyint(min_value=1,max_value=20) }}${{ fake.time(pattern='%H:%M:%S') }}Z
    picklist1__c:
      random_choice:
        - 'bravo'
        - 'alpha'
        - 'charlie'
        - 'delta'
        - 'echo'
        - 'foxtrot'
    dependentpicklist1__c:
      if:
        - choice:
            when: ${{picklist1__c=='alpha'}}
            pick:
              random_choice:
                - sierra
        - choice:
            when: ${{picklist1__c=='bravo'}}
            pick:
              random_choice:
                - sierra
                - tango
        - choice:
            when: ${{picklist1__c=='charlie'}}
            pick:
              random_choice:
                - sierra
                - tango
                - uniform
                - victor
        - choice:
            when: ${{picklist1__c=='delta'}}
            pick:
              random_choice:
                - sierra
                - tango
                - uniform
                - victor
        - choice:
            when: ${{picklist1__c=='echo'}}
            pick:
              random_choice:
                - sierra
                - tango
        - choice:
            when: ${{picklist1__c=='foxtrot'}}
            pick:
              random_choice:
                - sierra
    email1__c:
      fake: ascii_safe_email
    formulafield1__c:
      fake: first_name
    formulafield2__c:
      fake: last_name
    geolocation1__latitude__s:
      fake: latitude
    geolocation1__longitude__s:
      fake: longitude
    number1__c: ${{fake.pyint(min_value=0,max_value=1000000)}}
    percent1__c: ${{fake.pyint(min_value=0,max_value=100)}}
    phone1__c:
      fake: phone_number
    picklistmultiselect1__c: ${{ ';'.join(( fake.random_sample( elements=('alpha','bravo','charlie','delta','echo','foxtrot') ) )) }}
    text1__c:
      fake: sentence
    textencrypted1__c:
      fake: credit_card_number
    textarea1__c:
      fake: paragraph
    textarealong1__c:
      fake: paragraph
    textarearich1__c:
      fake: paragraph
    time1__c:
      fake: time
    url1__c:
      fake: url
```
