### ISSUE TITLE
SOQLDataset.shuffle generates an error when used in a macro

### ISSUE THREAD

**Issue by dcinzona** [SFDO-Tooling/Snowfakery#560]
If you use the SOQLDataset plugin in a macro, the system attempts to delete the file ([cleanup()](https://github.com/SFDO-Tooling/Snowfakery/blob/main/snowfakery/standard_plugins/Salesforce.py#L388)) when the context is closed using TempDirectory().cleanup()

If I move this same shuffle declaration into a recipe, not a macro called by the recipe, I no longer get the error.

**Recipe**
_Account.yml_
```
- plugin: snowfakery.standard_plugins.Salesforce.SOQLDataset
- plugin: snowfakery.standard_plugins.Salesforce.SalesforceQuery
- include_file: account.macro.yml
- object: Account
  include: account
  fields:
    __user:
      SOQLDataset.shuffle:
      #SalesforceQuery.random_record:
        fields: Id
        from: User
        where: IsActive = true  LIMIT 10
    OwnerId: ${{__user.Id}}
```

**Macrol**
_account.macro.yml_
```
- plugin: snowfakery.standard_plugins.Salesforce.SOQLDataset
- plugin: snowfakery.standard_plugins.Salesforce.SalesforceQuery
- macro: account
  fields:
    __user:
      SOQLDataset.shuffle:
      #SalesforceQuery.random_record:
        fields: Id, LastName
        from: User
        where: IsActive = true
    OwnerId: ${{__user.Id}}
    Name: ${{__user.LastName}}
```

I'm guessing that once the macro is loaded, it gets pulled out of memory and the context is closed, and so it's trying to clean up everything - but not sure why it is trying to call cleanup() on the actual `queryresults.db` rather than the enclosing directory.

Here is the stack trace:

```Traceback (most recent call last):
  File "C:\Users\GustavoTandeciarz\AppData\Local\Programs\Python\Python39\lib\weakref.py", line 591, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\GustavoTandeciarz\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 820, in _cleanup
    cls._rmtree(name)
  File "C:\Users\GustavoTandeciarz\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 816, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\GustavoTandeciarz\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\GustavoTandeciarz\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 627, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\GustavoTandeciarz\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 808, in onerror
    cls._rmtree(path)
  File "C:\Users\GustavoTandeciarz\AppData\Local\Programs\Python\Python39\lib\tempfile.py", line 816, in _rmtree
    _shutil.rmtree(name, onerror=onerror)
  File "C:\Users\GustavoTandeciarz\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 749, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\GustavoTandeciarz\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 608, in _rmtree_unsafe
    onerror(os.scandir, path, sys.exc_info())
  File "C:\Users\GustavoTandeciarz\AppData\Local\Programs\Python\Python39\lib\shutil.py", line 605, in _rmtree_unsafe
    with os.scandir(path) as scandir_it:
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\GUSTAV~1\\AppData\\Local\\Temp\\tmp3tsiuqwe\\queryresults.db'```
