### ISSUE TITLE
Custom Primary Key/Id

### ISSUE THREAD

**Issue by mitchwd** [SFDO-Tooling/Snowfakery#755]
Hey team,
Love the snowfakery tool, and use it often.
I'm working in a non-Salesforce env, and looking to generate a UUID4 as the id primary key, rather than an incrementing integer. 
Is this possible, or are you aware of any possible workarounds?

Thanks,
Mitch

**Comment by mitchwd** [comment]
Ah, looks like simply overriding the id _sort of_ works, except when using random references...
**Scenario 1: One object, overriding the id:**
```
- object: city
  count: 3
  fields:
    id: 
      fake: uuid4
    name:
      fake: firstName
```
Output: Works, but generates duplicate id columns. (One can be stripped manually)

**Scenario 2: Two objects, parent/child:**
```
- object: city
  count: 3
  fields:
    id: 
      fake: uuid4
    name:
      fake: city
   __people:
    - object: people
      count: 10
      fields:
        id: 
          fake: uuid4
       name: firstName
       city: 
         reference: city
```
Output: Works, but generates duplicate id columns.

**Scenario 3: Two objects, with random_reference:**
```
- object: city
  count: 3
  fields:
    id: 
      fake: uuid4
    name:
      fake: city
- object: people
  count: 10
  fields:
    id: 
      fake: uuid4
   name: firstName
   city: 
     random_reference: city
```
Output:
```
An error occurred. If you would like to see a Python traceback, use the --debug-internals option.
Error: Problem rendering value : '<' not supported between instances of 'str' and 'int'
```
:( Any tips on getting this third scenario to function?
