### ISSUE TITLE
Control output order of friends

### ISSUE THREAD

**Issue by gilesrapkinb** [SFDO-Tooling/Snowfakery#958]
Is there any way to control the output order of an object and its friends?

Given the following config:

```yaml
- object: Person
  fields:
    name: Dave
  friends:
    - object: Pet
      count: 2
      fields:
        species:
          random_choice:
            - Dog
            - Cat
        owner_id:
          reference: Person
```

When outputting json this would generate something like:

```json
[{"_table": "Pet", "id": 1, "species": "Dog", "owner_id": 1},
{"_table": "Pet", "id": 2, "species": "Cat", "owner_id": 1},
{"_table": "Person", "id": 1, "name": "Dave"}]
```

With a foreign key on the Pet table to the Person table inserting into a database in that order would fail, so ideally I'd like to have the top level object output first:

```json
[{"_table": "Person", "id": 1, "name": "Dave"},
{"_table": "Pet", "id": 1, "species": "Dog", "owner_id": 1},
{"_table": "Pet", "id": 2, "species": "Cat", "owner_id": 1}]
```

Is it possible to control the order of the output, so that friend objects are output after the main object?
